---
title: "Scholar Report"
output: html_document
params:
  n: NA
---

```{r setup, include=FALSE, echo = FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r load_pkgs}
library(magrittr)
library(purrr)
library(plotly)
library(ggplot2)
library(stringr)
library(readr)
library(DT)
library(kableExtra)
```

```{r load_data}
course_grant_df <- read_rds(here("data/course_grant_df.rds"))
cite_df_list <- read_rds(here("data/cite_df_list.rds"))
```


```{r get_param}
fullname = params$n
```


```{r position}
grant <- course_grant_df[which(course_grant_df$Fullname == fullname), ]
pos <- grant[, "Position"][1]
```

```{r g_count}
grant <- course_grant_df[which(course_grant_df$Fullname == fullname), ]
grant_count <- nrow(grant)
```

```{r g_amount}
grant <- course_grant_df[which(course_grant_df$Fullname == fullname), ]
grant_amount <- sum(grant$totalCostAmount)
```

```{r c_count}
t <- cite_df_list[[fullname]]
t <- t[, colnames(t) %in% regmatches(colnames(t),regexpr("X\\d{4}",colnames(t)))]
colnames(t) <- str_split(colnames(t), pattern = fixed("X"), simplify = T)[,2]
cites <- sum(t)
```

```{r p_count}
t <- cite_df_list[[fullname]]
t <- t[, colnames(t) %in% regmatches(colnames(t),regexpr("X\\d{4}",colnames(t)))]
colnames(t) <- str_split(colnames(t), pattern = fixed("X"), simplify = T)[,2]
pubs <- nrow(t)
```


```{r}
stats <- data.frame(fullname,
                    pos,
                    grant_count,
                    grant_amount,
                    cites,
                    pubs)
names(stats) <- c("Name", "Position", "Total Grants", "Total Grant Funding", "Total Citations", "Total Publications")
stats %>% 
kable("html") %>%
  kable_styling(bootstrap_options = c("hover", 
                                      "condensed", 
                                      "responsive"))
```

```{r cite_dot}
t <- cite_df_list[[fullname]]
t <- t[, colnames(t) %in% regmatches(colnames(t),regexpr("X\\d{4}",colnames(t)))]
colnames(t) <- str_split(colnames(t), pattern = fixed("X"), simplify = T)[,2]
citey <- colSums(t)
cy <- data.frame(as.numeric(names(citey)), citey)
colnames(cy) <- c("Year", "Count")
if (nrow(cy) < 7){
    k = 1
} else if (nrow(cy) < 15){
    k = 2
}else if (nrow(cy) < 22){
    k = 3
}else {
    k = 5
}
cite_dot <- ggplot(data = cy, aes(Year, Count, group = 1)) + geom_point(color = "#F8766D") + geom_line(color = "#F8766D") + labs(Year = "Year", y = "Total Citations", title = "Total Citations By Year") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black")) + scale_x_continuous(breaks=seq(min(cy$Year), max(cy$Year), by = k))
cite_dot %>% 
    ggplotly()
```

```{r}
t <- cite_df_list[[fullname]]
if (sum(colnames(t) == "publication.date.1") == 1){
    t$publication.date <- t$publication.date.1
}
t <- t$publication.date
t <- t[!is.na(t)]
yr <- data.frame(str_split(t, pattern = fixed("/"), simplify = T)[,1])
yr <- table(yr)
yr <- data.frame(as.numeric(names(yr)), yr)
colnames(yr) <- c("Year", "name", "Count")
if (nrow(yr) < 7){
    k = 1
} else if (nrow(yr) < 15){
    k = 2
}else if (nrow(yr) < 22){
    k = 3
}else {
    k = 5
}
pub_dot <- ggplot(data = yr, aes(Year, Count, group = 1)) + geom_point(color = "#619CFF") + geom_line(color = "#619CFF") + labs(x = "Year", y = "Total Publications", title = "Total Publications By Year")+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black")) + scale_x_continuous(breaks=seq(min(yr$Year), max(yr$Year), by = k)) 

pub_dot %>% 
    ggplotly()
```
